/* We need to include all components that take part in any testing 
 * This is so webpack can add them to build.
 * Previously was doing this with Lazy loading but this is too much overhead and too slow for simple
 * AB Testing. Lazy loading more suited to EDS widgets
 * 
 * This file could be autogenerated perhaps as it is just a dictionary lookup
 * 
 */
import React from "react";
import MedicalSearch from "../containers/medical-search";
import AcademicSearch from "../containers/academic-search";


export const getComponentInstance = (componentName) => {
  switch (componentName) {
    case "MedicalSearch":
      return <MedicalSearch/>;
    case "AcademicSearch":
      return <AcademicSearch/>;
    default:
      return <div>Invalid Experiment</div>;
  };
} 